// @stms/shared - Error Codes
// Standardized error codes for consistent error handling across FE/BE

export const ERROR_CODES = {
  // Validation
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INVALID_INPUT: 'INVALID_INPUT',
  MISSING_REQUIRED_FIELD: 'MISSING_REQUIRED_FIELD',

  // Authentication
  UNAUTHORIZED: 'UNAUTHORIZED',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  TOKEN_INVALID: 'TOKEN_INVALID',
  TOKEN_REVOKED: 'TOKEN_REVOKED',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  ACCOUNT_DISABLED: 'ACCOUNT_DISABLED',
  ACCOUNT_NOT_VERIFIED: 'ACCOUNT_NOT_VERIFIED',
  REFRESH_TOKEN_EXPIRED: 'REFRESH_TOKEN_EXPIRED',
  REFRESH_TOKEN_INVALID: 'REFRESH_TOKEN_INVALID',
  REFRESH_TOKEN_REVOKED: 'REFRESH_TOKEN_REVOKED',

  // Authorization
  FORBIDDEN: 'FORBIDDEN',
  INSUFFICIENT_PERMISSIONS: 'INSUFFICIENT_PERMISSIONS',
  INSUFFICIENT_ROLE: 'INSUFFICIENT_ROLE',
  CLUB_ACCESS_DENIED: 'CLUB_ACCESS_DENIED',
  MEMBERSHIP_NOT_FOUND: 'MEMBERSHIP_NOT_FOUND',
  MEMBERSHIP_INACTIVE: 'MEMBERSHIP_INACTIVE',
  CANNOT_MODIFY_OWN_ROLE: 'CANNOT_MODIFY_OWN_ROLE',
  CANNOT_DELETE_SELF: 'CANNOT_DELETE_SELF',
  CANNOT_ASSIGN_SYSTEM_ADMIN: 'CANNOT_ASSIGN_SYSTEM_ADMIN',

  // Resource
  NOT_FOUND: 'NOT_FOUND',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  CLUB_NOT_FOUND: 'CLUB_NOT_FOUND',
  ATHLETE_NOT_FOUND: 'ATHLETE_NOT_FOUND',
  WORKOUT_NOT_FOUND: 'WORKOUT_NOT_FOUND',
  SESSION_NOT_FOUND: 'SESSION_NOT_FOUND',
  INJURY_NOT_FOUND: 'INJURY_NOT_FOUND',
  PERMISSION_LETTER_NOT_FOUND: 'PERMISSION_LETTER_NOT_FOUND',
  TEMPLATE_NOT_FOUND: 'TEMPLATE_NOT_FOUND',

  // Conflict
  CONFLICT: 'CONFLICT',
  EMAIL_ALREADY_EXISTS: 'EMAIL_ALREADY_EXISTS',
  SLUG_ALREADY_EXISTS: 'SLUG_ALREADY_EXISTS',
  USER_ALREADY_MEMBER: 'USER_ALREADY_MEMBER',
  DUPLICATE_RESOURCE: 'DUPLICATE_RESOURCE',

  // Rate Limiting
  RATE_LIMITED: 'RATE_LIMITED',
  TOO_MANY_REQUESTS: 'TOO_MANY_REQUESTS',
  AUTH_RATE_LIMITED: 'AUTH_RATE_LIMITED',

  // Server
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',
  DATABASE_ERROR: 'DATABASE_ERROR',
  EXTERNAL_SERVICE_ERROR: 'EXTERNAL_SERVICE_ERROR',
  FIREBASE_ERROR: 'FIREBASE_ERROR',
  REDIS_ERROR: 'REDIS_ERROR',

  // File Upload
  FILE_TOO_LARGE: 'FILE_TOO_LARGE',
  INVALID_FILE_TYPE: 'INVALID_FILE_TYPE',
  UPLOAD_FAILED: 'UPLOAD_FAILED',

  // Business Logic
  INVALID_STATE_TRANSITION: 'INVALID_STATE_TRANSITION',
  OPERATION_NOT_ALLOWED: 'OPERATION_NOT_ALLOWED',
  QUOTA_EXCEEDED: 'QUOTA_EXCEEDED',
  FEATURE_DISABLED: 'FEATURE_DISABLED',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];

// ==================== ERROR CODE UTILITIES ====================

/**
 * Check if an error code is valid
 */
export function isValidErrorCode(code: string): code is ErrorCode {
  return Object.values(ERROR_CODES).includes(code as ErrorCode);
}

/**
 * Get HTTP status code for an error code
 */
export function getHttpStatusForErrorCode(code: ErrorCode): number {
  const statusMap: Record<ErrorCode, number> = {
    // Validation
    [ERROR_CODES.VALIDATION_ERROR]: 400,
    [ERROR_CODES.INVALID_INPUT]: 400,
    [ERROR_CODES.MISSING_REQUIRED_FIELD]: 400,

    // Authentication
    [ERROR_CODES.UNAUTHORIZED]: 401,
    [ERROR_CODES.TOKEN_EXPIRED]: 401,
    [ERROR_CODES.TOKEN_INVALID]: 401,
    [ERROR_CODES.TOKEN_REVOKED]: 401,
    [ERROR_CODES.INVALID_CREDENTIALS]: 401,
    [ERROR_CODES.ACCOUNT_DISABLED]: 403,
    [ERROR_CODES.ACCOUNT_NOT_VERIFIED]: 403,
    [ERROR_CODES.REFRESH_TOKEN_EXPIRED]: 401,
    [ERROR_CODES.REFRESH_TOKEN_INVALID]: 401,
    [ERROR_CODES.REFRESH_TOKEN_REVOKED]: 401,

    // Authorization
    [ERROR_CODES.FORBIDDEN]: 403,
    [ERROR_CODES.INSUFFICIENT_PERMISSIONS]: 403,
    [ERROR_CODES.INSUFFICIENT_ROLE]: 403,
    [ERROR_CODES.CLUB_ACCESS_DENIED]: 403,
    [ERROR_CODES.MEMBERSHIP_NOT_FOUND]: 403,
    [ERROR_CODES.MEMBERSHIP_INACTIVE]: 403,
    [ERROR_CODES.CANNOT_MODIFY_OWN_ROLE]: 403,
    [ERROR_CODES.CANNOT_DELETE_SELF]: 403,
    [ERROR_CODES.CANNOT_ASSIGN_SYSTEM_ADMIN]: 403,

    // Resource
    [ERROR_CODES.NOT_FOUND]: 404,
    [ERROR_CODES.USER_NOT_FOUND]: 404,
    [ERROR_CODES.CLUB_NOT_FOUND]: 404,
    [ERROR_CODES.ATHLETE_NOT_FOUND]: 404,
    [ERROR_CODES.WORKOUT_NOT_FOUND]: 404,
    [ERROR_CODES.SESSION_NOT_FOUND]: 404,
    [ERROR_CODES.INJURY_NOT_FOUND]: 404,
    [ERROR_CODES.PERMISSION_LETTER_NOT_FOUND]: 404,
    [ERROR_CODES.TEMPLATE_NOT_FOUND]: 404,

    // Conflict
    [ERROR_CODES.CONFLICT]: 409,
    [ERROR_CODES.EMAIL_ALREADY_EXISTS]: 409,
    [ERROR_CODES.SLUG_ALREADY_EXISTS]: 409,
    [ERROR_CODES.USER_ALREADY_MEMBER]: 409,
    [ERROR_CODES.DUPLICATE_RESOURCE]: 409,

    // Rate Limiting
    [ERROR_CODES.RATE_LIMITED]: 429,
    [ERROR_CODES.TOO_MANY_REQUESTS]: 429,
    [ERROR_CODES.AUTH_RATE_LIMITED]: 429,

    // Server
    [ERROR_CODES.INTERNAL_ERROR]: 500,
    [ERROR_CODES.SERVICE_UNAVAILABLE]: 503,
    [ERROR_CODES.DATABASE_ERROR]: 500,
    [ERROR_CODES.EXTERNAL_SERVICE_ERROR]: 502,
    [ERROR_CODES.FIREBASE_ERROR]: 500,
    [ERROR_CODES.REDIS_ERROR]: 500,

    // File Upload
    [ERROR_CODES.FILE_TOO_LARGE]: 413,
    [ERROR_CODES.INVALID_FILE_TYPE]: 415,
    [ERROR_CODES.UPLOAD_FAILED]: 500,

    // Business Logic
    [ERROR_CODES.INVALID_STATE_TRANSITION]: 400,
    [ERROR_CODES.OPERATION_NOT_ALLOWED]: 403,
    [ERROR_CODES.QUOTA_EXCEEDED]: 429,
    [ERROR_CODES.FEATURE_DISABLED]: 501,
  };

  return statusMap[code] ?? 500;
}

/**
 * Check if error is client-side (4xx)
 */
export function isClientError(code: ErrorCode): boolean {
  const status = getHttpStatusForErrorCode(code);
  return status >= 400 && status < 500;
}

/**
 * Check if error is server-side (5xx)
 */
export function isServerError(code: ErrorCode): boolean {
  const status = getHttpStatusForErrorCode(code);
  return status >= 500;
}

/**
 * Check if error is auth-related
 */
export function isAuthError(code: ErrorCode): boolean {
  return code.startsWith('TOKEN_') ||
    code === ERROR_CODES.UNAUTHORIZED ||
    code === ERROR_CODES.INVALID_CREDENTIALS ||
    code === ERROR_CODES.ACCOUNT_DISABLED ||
    code === ERROR_CODES.ACCOUNT_NOT_VERIFIED ||
    code === ERROR_CODES.REFRESH_TOKEN_EXPIRED ||
    code === ERROR_CODES.REFRESH_TOKEN_INVALID ||
    code === ERROR_CODES.REFRESH_TOKEN_REVOKED;
}

/**
 * Check if error is rate-limit related
 */
export function isRateLimitError(code: ErrorCode): boolean {
  return code === ERROR_CODES.RATE_LIMITED ||
    code === ERROR_CODES.TOO_MANY_REQUESTS ||
    code === ERROR_CODES.AUTH_RATE_LIMITED ||
    code === ERROR_CODES.QUOTA_EXCEEDED;
}