import React, { useEffect, useState } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import { ArrowLeft, HeartPulse, Plus, Save } from 'lucide-react';
import { toast } from 'sonner';
import { Badge, Button, Card, CardContent, Input, Modal, Select } from '@/components/ui';
import { injuryApi } from '@/services/api';
import { useAuth } from '@/context/AuthContext';

const today = () => new Date().toISOString().slice(0, 10);
export function InjuryDetail() {
  const { id = '' } = useParams(); const navigate = useNavigate(); const { hasPermission } = useAuth();
  const [injury, setInjury] = useState<any>(null); const [wellness, setWellness] = useState<any[]>([]); const [loading, setLoading] = useState(true); const [wellnessOpen, setWellnessOpen] = useState(false); const [rehabOpen, setRehabOpen] = useState(false); const [saving, setSaving] = useState(false);
  const [check, setCheck] = useState({ date: today(), pain: 0, fatigue: 5, sleepHours: '', note: '' }); const [rehab, setRehab] = useState({ name: '', instructions: '', dueDate: '' });
  const canWrite = hasPermission('injury:write'); const canRtp = hasPermission('injury:rtp'); const canSelfLog = hasPermission('injury:write:own');
  const load = async () => { setLoading(true); try { const [detail, logs] = await Promise.all([injuryApi.getOne(id), injuryApi.getWellness(id)]); setInjury(detail); setWellness(logs); } catch (error: any) { toast.error(error.message || 'Could not load injury record'); setInjury(null); } finally { setLoading(false); } };
  useEffect(() => { void load(); /* data key is stable for this route */ }, [id]);
  const saveWellness = async (event: React.FormEvent) => { event.preventDefault(); setSaving(true); try { await injuryApi.addWellness(id, { ...check, pain: Number(check.pain), fatigue: Number(check.fatigue), sleepHours: check.sleepHours ? Number(check.sleepHours) : undefined }); toast.success('Wellbeing check saved'); setWellnessOpen(false); await load(); } catch (error: any) { toast.error(error.message || 'Could not save wellbeing check'); } finally { setSaving(false); } };
  const saveRehab = async (event: React.FormEvent) => { event.preventDefault(); setSaving(true); try { await injuryApi.addRehabTask(id, { ...rehab, dueDate: rehab.dueDate || undefined }); toast.success('Recovery step added'); setRehabOpen(false); setRehab({ name: '', instructions: '', dueDate: '' }); await load(); } catch (error: any) { toast.error(error.message || 'Could not add recovery step'); } finally { setSaving(false); } };
  const setRtp = async (status: string) => { try { const updated = await injuryApi.updateRtp(id, { status, phase: status === 'rehabilitating' ? 'Rehabilitation' : status === 'returning' ? 'Return to training' : status === 'resolved' ? 'Cleared' : 'Assessment' }); setInjury(updated); toast.success('Return-to-training status updated'); } catch (error: any) { toast.error(error.message || 'Could not update recovery status'); } };
  if (loading) return <div role="status" className="py-20 text-center text-text-secondary">Loading injury record…</div>;
  if (!injury) return <div className="py-16 text-center"><h1 className="text-xl font-semibold text-text-primary">Injury record unavailable</h1><Button className="mt-5" variant="outline" onClick={() => navigate('/injuries')}>Back to injuries</Button></div>;
  return <div className="mx-auto max-w-4xl space-y-6"><Button variant="ghost" size="sm" onClick={() => navigate('/injuries')} leftIcon={<ArrowLeft className="h-4 w-4" />}>Injury records</Button>
    <section className="surface-raised p-6 sm:p-8"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-sm font-semibold text-sky-400">RECOVERY RECORD</p><h1 className="mt-2 text-3xl font-bold text-text-primary">{injury.type}</h1><p className="mt-2 text-text-secondary">{injury.bodyPart} · {injury.laterality} · Onset {injury.onsetDate}</p></div><Badge variant={injury.status === 'resolved' ? 'success' : injury.status === 'returning' ? 'gold' : 'primary'}>{injury.status}</Badge></div><div className="mt-5 flex flex-wrap gap-2">{injury.restrictions?.map((item: string) => <Badge key={item} variant="outline">{item}</Badge>)}</div>{injury.mechanism && <p className="mt-4 text-sm leading-relaxed text-text-secondary">{injury.mechanism}</p>}</section>
    <Card><CardContent className="space-y-4 p-5"><div className="flex items-start justify-between gap-3"><div><h2 className="font-semibold text-text-primary">Recovery plan</h2><p className="mt-1 text-sm text-text-secondary">{injury.phase || 'Initial assessment'}{injury.expectedReturnDate ? ` · Expected return ${injury.expectedReturnDate}` : ''}</p></div>{canWrite && <Button variant="outline" size="sm" onClick={() => setRehabOpen(true)} leftIcon={<Plus className="h-4 w-4" />}>Add step</Button>}</div>{injury.rehabPlan?.length ? <div className="space-y-2">{injury.rehabPlan.map((item: any) => <div key={item._id} className="rounded-lg border border-border p-3"><p className="font-medium text-text-primary">{item.name}</p>{item.instructions && <p className="mt-1 text-sm text-text-secondary">{item.instructions}</p>}{item.dueDate && <p className="mt-1 text-xs text-text-muted">Due {item.dueDate}</p>}</div>)}</div> : <p className="rounded-lg border border-dashed border-border p-5 text-center text-sm text-text-secondary">No recovery steps recorded yet.</p>}{canRtp && <div className="flex flex-wrap gap-2 border-t border-border pt-4">{[['active', 'Active'], ['rehabilitating', 'Rehabilitating'], ['returning', 'Return to training'], ['resolved', 'Resolve injury']].map(([status, label]) => <Button key={status} size="sm" variant={injury.status === status ? 'primary' : 'outline'} onClick={() => void setRtp(status)}>{label}</Button>)}</div>}</CardContent></Card>
    <Card><CardContent className="p-5"><div className="flex items-center justify-between gap-3"><div><h2 className="font-semibold text-text-primary">Daily wellbeing</h2><p className="mt-1 text-sm text-text-secondary">Pain and fatigue check-ins help follow recovery over time.</p></div>{(canWrite || canSelfLog) && <Button size="sm" onClick={() => setWellnessOpen(true)} leftIcon={<HeartPulse className="h-4 w-4" />}>Log today</Button>}</div>{wellness.length ? <div className="mt-4 divide-y divide-border">{wellness.map(row => <div key={row.id} className="flex flex-wrap items-center justify-between gap-2 py-3"><div><p className="font-medium text-text-primary">{row.date}</p><p className="text-sm text-text-secondary">Pain {row.pain}/10 · Fatigue {row.fatigue}/10{row.sleepHours ? ` · Sleep ${row.sleepHours}h` : ''}</p>{row.note && <p className="mt-1 text-sm text-text-muted">{row.note}</p>}</div></div>)}</div> : <p className="mt-5 text-sm text-text-secondary">No wellbeing check-ins have been recorded.</p>}</CardContent></Card>
    <Modal isOpen={wellnessOpen} onClose={() => setWellnessOpen(false)} title="Daily wellbeing check" description="Use the same scale each day: 0 is none, 10 is highest." size="sm"><form onSubmit={saveWellness} className="space-y-4"><Input label="Date" type="date" value={check.date} onChange={event => setCheck({ ...check, date: event.target.value })} /><Input label={`Pain · ${check.pain}/10`} type="range" min={0} max={10} value={check.pain} onChange={event => setCheck({ ...check, pain: Number(event.target.value) })} /><Input label={`Fatigue · ${check.fatigue}/10`} type="range" min={0} max={10} value={check.fatigue} onChange={event => setCheck({ ...check, fatigue: Number(event.target.value) })} /><Input label="Sleep (hours)" type="number" min={0} max={24} step="0.5" value={check.sleepHours} onChange={event => setCheck({ ...check, sleepHours: event.target.value })} /><Input label="Note (optional)" value={check.note} maxLength={500} onChange={event => setCheck({ ...check, note: event.target.value })} /><div className="flex justify-end gap-2"><Button type="button" variant="ghost" onClick={() => setWellnessOpen(false)}>Cancel</Button><Button type="submit" loading={saving} leftIcon={<Save className="h-4 w-4" />}>Save check-in</Button></div></form></Modal>
    <Modal isOpen={rehabOpen} onClose={() => setRehabOpen(false)} title="Add recovery step" size="sm"><form onSubmit={saveRehab} className="space-y-4"><Input label="Step" required value={rehab.name} onChange={event => setRehab({ ...rehab, name: event.target.value })} /><label className="block text-sm text-text-secondary">Instructions<textarea className="mt-1 min-h-20 w-full rounded-lg border border-border bg-cold-900 px-3 py-2 text-text-primary" value={rehab.instructions} onChange={event => setRehab({ ...rehab, instructions: event.target.value })} /></label><Input label="Target date" type="date" value={rehab.dueDate} onChange={event => setRehab({ ...rehab, dueDate: event.target.value })} /><div className="flex justify-end gap-2"><Button type="button" variant="ghost" onClick={() => setRehabOpen(false)}>Cancel</Button><Button type="submit" loading={saving}>Add step</Button></div></form></Modal>
  </div>;
}
