import React, { useCallback, useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { Activity, ArrowRight, Plus } from 'lucide-react';
import { toast } from 'sonner';
import { Badge, Button, Card, CardContent, Input, Modal, Select } from '@/components/ui';
import { athleteApi, injuryApi } from '@/services/api';
import { useAuth } from '@/context/AuthContext';

const today = () => new Date().toISOString().slice(0, 10);
export function InjuriesList() {
  const { hasPermission } = useAuth();
  const [rows, setRows] = useState<any[]>([]); const [athletes, setAthletes] = useState<any[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [open, setOpen] = useState(false); const [saving, setSaving] = useState(false);
  const [form, setForm] = useState({ athleteId: '', type: '', bodyPart: '', laterality: 'not_applicable', onsetDate: today(), severity: 1, mechanism: '', diagnosisSource: 'self', diagnosis: '', expectedReturnDate: '' });
  const canWrite = hasPermission('injury:write'); const canWriteOwn = hasPermission('injury:write:own'); const coach = canWrite;
  const load = useCallback(async () => { setLoading(true); setError(''); try { const [injuries, roster] = await Promise.all([injuryApi.get(), coach ? athleteApi.getAthletes({ limit: 100 }) : Promise.resolve(null)]); setRows(injuries); setAthletes(roster?.data || []); } catch (cause: any) { setError(cause.message || 'Could not load injury records'); } finally { setLoading(false); } }, [coach]);
  useEffect(() => { void load(); }, [load]);
  const save = async (event: React.FormEvent) => { event.preventDefault(); setSaving(true); try { await injuryApi.create({ ...form, athleteId: coach ? form.athleteId : undefined, severity: Number(form.severity), expectedReturnDate: form.expectedReturnDate || null }); toast.success('Injury record saved'); setOpen(false); await load(); } catch (cause: any) { toast.error(cause.message || 'Could not save injury'); } finally { setSaving(false); } };

  return <div className="mx-auto max-w-6xl space-y-6">
    <section className="surface-raised relative overflow-hidden p-6 sm:p-8"><div className="absolute right-0 top-0 h-full w-1.5 bg-gradient-to-b from-sky-400 via-sky-500 to-amber-400" /><div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-sm font-semibold text-sky-400">SPRINT 7 · WELLBEING</p><h1 className="mt-2 text-3xl font-bold text-text-primary">Injury & return to training</h1><p className="mt-2 max-w-xl text-text-secondary">Keep injury status, recovery steps, and daily wellbeing notes together with access limited to the athlete and club staff.</p></div>{(canWrite || canWriteOwn) && <Button onClick={() => setOpen(true)} leftIcon={<Plus className="h-4 w-4" />}>Report an injury</Button>}</div></section>
    <Card><CardContent className="p-0"><div className="border-b border-border px-5 py-4"><h2 className="font-semibold text-text-primary">Injury records</h2><p className="mt-1 text-sm text-text-secondary">{loading ? 'Loading records…' : `${rows.length} records`}</p></div>{loading ? <div role="status" className="py-16 text-center text-text-secondary">Loading injury records…</div> : error ? <div className="py-14 text-center"><p role="alert">{error}</p><Button className="mt-4" variant="outline" onClick={() => void load()}>Try again</Button></div> : rows.length === 0 ? <div className="py-16 text-center"><Activity className="mx-auto h-10 w-10 text-text-muted" /><h3 className="mt-4 font-semibold text-text-primary">No injury records</h3><p className="mt-2 text-sm text-text-secondary">An athlete or coach can record a new injury when support is needed.</p></div> : <div className="divide-y divide-border">{rows.map(row => <Link key={row.id} to={`/injuries/${row.id}`} className="flex flex-col gap-3 px-5 py-4 hover:bg-cold-800/30 sm:flex-row sm:items-center"><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h3 className="font-semibold text-text-primary">{row.type} · {row.bodyPart} {row.laterality !== 'not_applicable' ? `(${row.laterality})` : ''}</h3><Badge variant={row.status === 'resolved' ? 'success' : row.status === 'returning' ? 'gold' : 'primary'}>{row.status}</Badge></div><p className="mt-1 text-sm text-text-secondary">Onset {row.onsetDate} · Severity {row.severity}/3{row.expectedReturnDate ? ` · Expected return ${row.expectedReturnDate}` : ''}</p><p className="mt-1 text-sm text-text-muted">{row.restrictions?.length ? `Restrictions: ${row.restrictions.join(', ')}` : 'No restrictions recorded'}</p></div><ArrowRight className="h-4 w-4 text-sky-400" /></Link>)}</div>}</CardContent></Card>
    <Modal isOpen={open} onClose={() => setOpen(false)} title="Report an injury" description="Record the issue and the date it started. Coaches can add recovery details." size="md"><form onSubmit={save} className="space-y-4">{coach && <Select label="Athlete" required value={form.athleteId} onChange={event => setForm({ ...form, athleteId: event.target.value })} options={[{ value: '', label: 'Choose an athlete' }, ...athletes.map(athlete => ({ value: athlete.id, label: `${athlete.firstName} ${athlete.lastName}` }))]} />}<div className="grid gap-4 sm:grid-cols-2"><Input label="Injury / issue" required maxLength={100} value={form.type} onChange={event => setForm({ ...form, type: event.target.value })} placeholder="Hamstring strain" /><Input label="Body part" required maxLength={60} value={form.bodyPart} onChange={event => setForm({ ...form, bodyPart: event.target.value })} placeholder="Thigh" /></div><div className="grid gap-4 sm:grid-cols-3"><Select label="Side" value={form.laterality} onChange={event => setForm({ ...form, laterality: event.target.value })} options={[{ value: 'not_applicable', label: 'Not applicable' }, { value: 'left', label: 'Left' }, { value: 'right', label: 'Right' }, { value: 'bilateral', label: 'Both sides' }]} /><Select label="Severity" value={String(form.severity)} onChange={event => setForm({ ...form, severity: Number(event.target.value) })} options={[{ value: '1', label: 'Grade 1 · mild' }, { value: '2', label: 'Grade 2 · moderate' }, { value: '3', label: 'Grade 3 · severe' }]} /><Input label="Onset date" type="date" required value={form.onsetDate} onChange={event => setForm({ ...form, onsetDate: event.target.value })} /></div>{coach && <><Select label="Diagnosis source" value={form.diagnosisSource} onChange={event => setForm({ ...form, diagnosisSource: event.target.value })} options={['coach', 'physio', 'doctor', 'self', 'other'].map(value => ({ value, label: value }))} /><label className="block text-sm text-text-secondary">Mechanism / diagnosis notes<textarea className="mt-1 min-h-20 w-full rounded-lg border border-border bg-cold-900 px-3 py-2 text-text-primary" maxLength={1200} value={form.mechanism} onChange={event => setForm({ ...form, mechanism: event.target.value })} /></label></>}<div className="flex justify-end gap-2"><Button type="button" variant="ghost" onClick={() => setOpen(false)}>Cancel</Button><Button type="submit" loading={saving} disabled={coach && !form.athleteId}>Save record</Button></div></form></Modal>
  </div>;
}
