import React, { useCallback, useEffect, useState } from 'react';
import { Check, Clipboard, FileText, Plus } from 'lucide-react';
import { toast } from 'sonner';
import { Badge, Button, Card, CardContent, Input, Modal, Select } from '@/components/ui';
import { useAuth } from '@/context/AuthContext';
import { athleteApi, permissionApi } from '@/services/api';

const today = () => new Date().toISOString().slice(0, 10);
const letterTypes = [{ value: 'hod', label: 'HOD permission' }, { value: 'faculty', label: 'Faculty permission' }, { value: 'hostel', label: 'Hostel permission' }, { value: 'competition', label: 'Competition participation' }, { value: 'travel', label: 'Travel permission' }, { value: 'attendance', label: 'Attendance adjustment' }, { value: 'medical_leave', label: 'Medical leave' }, { value: 'training_camp', label: 'Training camp' }];
export function PermissionsList() {
  const { hasPermission } = useAuth();
  const [tab, setTab] = useState<'events' | 'letters'>('events'); const [events, setEvents] = useState<any[]>([]); const [letters, setLetters] = useState<any[]>([]); const [athletes, setAthletes] = useState<any[]>([]);
  const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [eventOpen, setEventOpen] = useState(false); const [generateFor, setGenerateFor] = useState<any>(null); const [createdOpen, setCreatedOpen] = useState(false); const [createdLinks, setCreatedLinks] = useState<any[]>([]); const [saving, setSaving] = useState(false);
  const [eventForm, setEventForm] = useState({ name: '', date: today(), venue: '', type: 'competition', description: '' }); const [selectedAthletes, setSelectedAthletes] = useState<string[]>([]); const [selectedTypes, setSelectedTypes] = useState<string[]>(['competition']);
  const canWrite = hasPermission('permission:write'); const canApprove = hasPermission('permission:approve');
  const load = useCallback(async () => { setLoading(true); setError(''); try { const [eventRows, letterRows, roster] = await Promise.all([permissionApi.getEvents(), permissionApi.getLetters(), canWrite ? athleteApi.getAthletes({ limit: 100 }) : Promise.resolve(null)]); setEvents(eventRows); setLetters(letterRows); setAthletes(roster?.data || []); } catch (cause: any) { setError(cause.message || 'Could not load permission workflows'); } finally { setLoading(false); } }, [canWrite]);
  useEffect(() => { void load(); }, [load]);
  const createEvent = async (event: React.FormEvent) => { event.preventDefault(); setSaving(true); try { const created = await permissionApi.createEvent(eventForm); toast.success('Permission event created'); setEventOpen(false); setGenerateFor(created); await load(); } catch (cause: any) { toast.error(cause.message || 'Could not create event'); } finally { setSaving(false); } };
  const generateLetters = async () => { if (!generateFor || !selectedAthletes.length || !selectedTypes.length) return; setSaving(true); try { const result = await permissionApi.generateLetters(generateFor.id, { athleteIds: selectedAthletes, types: selectedTypes }); setCreatedLinks(result.letters || []); setCreatedOpen(true); setGenerateFor(null); setSelectedAthletes([]); await load(); } catch (cause: any) { toast.error(cause.message || 'Could not generate letters'); } finally { setSaving(false); } };
  const submit = async (letter: any) => { try { await permissionApi.submitLetter(letter.id); toast.success('Letter submitted for review'); await load(); } catch (cause: any) { toast.error(cause.message || 'Could not submit letter'); } };
  const decide = async (letter: any, decision: 'approved' | 'rejected') => { try { await permissionApi.decideLetter(letter.id, decision); toast.success(`Letter ${decision}`); await load(); } catch (cause: any) { toast.error(cause.message || 'Could not review letter'); } };
  const copy = async (text: string) => { try { await navigator.clipboard.writeText(text); toast.success('Copied'); } catch { toast.error('Clipboard access is unavailable. Select and copy the text.'); } };
  const toggle = (values: string[], value: string, update: (next: string[]) => void) => update(values.includes(value) ? values.filter(item => item !== value) : [...values, value]);

  return <div className="mx-auto max-w-6xl space-y-6">
    <section className="surface-raised relative overflow-hidden p-6 sm:p-8"><div className="absolute right-0 top-0 h-full w-1.5 bg-gradient-to-b from-sky-400 via-sky-500 to-amber-400" /><div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-sm font-semibold text-sky-400">SPRINT 7 · EVENT PERMISSIONS</p><h1 className="mt-2 text-3xl font-bold text-text-primary">Permission letters</h1><p className="mt-2 max-w-xl text-text-secondary">Generate athlete-specific request letters and track them through submission, review, and verification.</p></div>{canWrite && <Button onClick={() => setEventOpen(true)} leftIcon={<Plus className="h-4 w-4" />}>Create event</Button>}</div></section>
    <div className="flex gap-2 border-b border-border pb-2"><button onClick={() => setTab('events')} className={`rounded-lg px-4 py-2 text-sm ${tab === 'events' ? 'bg-sky-400/10 text-sky-300' : 'text-text-secondary'}`}>Events</button><button onClick={() => setTab('letters')} className={`rounded-lg px-4 py-2 text-sm ${tab === 'letters' ? 'bg-sky-400/10 text-sky-300' : 'text-text-secondary'}`}>Letters</button></div>
    <Card><CardContent className="p-0"><div className="border-b border-border px-5 py-4"><h2 className="font-semibold text-text-primary">{tab === 'events' ? 'Permission events' : 'Generated letters'}</h2><p className="mt-1 text-sm text-text-secondary">{loading ? 'Loading…' : tab === 'events' ? `${events.length} events` : `${letters.length} letters`}</p></div>{loading ? <div role="status" className="py-16 text-center text-text-secondary">Loading permission records…</div> : error ? <div className="py-14 text-center"><p role="alert">{error}</p><Button className="mt-4" variant="outline" onClick={() => void load()}>Try again</Button></div> : tab === 'events' ? events.length === 0 ? <div className="py-16 text-center"><FileText className="mx-auto h-10 w-10 text-text-muted" /><h3 className="mt-4 font-semibold text-text-primary">No permission events</h3><p className="mt-2 text-sm text-text-secondary">Create an event to prepare permission requests for participating athletes.</p></div> : <div className="divide-y divide-border">{events.map(event => <div key={event.id} className="flex flex-col gap-3 px-5 py-4 sm:flex-row sm:items-center sm:justify-between"><div><h3 className="font-semibold text-text-primary">{event.name}</h3><p className="mt-1 text-sm text-text-secondary">{event.date} · {event.venue || 'Venue not set'} · {event.type.replace('_', ' ')}</p></div>{canWrite && <Button size="sm" variant="outline" onClick={() => setGenerateFor(event)}>Generate letters</Button>}</div>)}</div> : letters.length === 0 ? <div className="py-16 text-center text-text-secondary">No letters generated yet.</div> : <div className="divide-y divide-border">{letters.map(letter => <div key={letter.id} className="flex flex-col gap-3 px-5 py-4"><div className="flex flex-wrap items-center justify-between gap-3"><div><h3 className="font-semibold text-text-primary">{letter.athleteName} · {letter.templateId.replace('_', ' ')}</h3><p className="mt-1 text-sm text-text-secondary">{letter.status.replace('_', ' ')} · Created {new Date(letter.createdAt).toLocaleDateString()}</p></div><Badge variant={letter.status === 'approved' ? 'success' : letter.status === 'rejected' ? 'danger' : 'neutral'}>{letter.status}</Badge></div><details><summary className="cursor-pointer text-sm text-sky-400">Review letter content</summary><pre className="mt-3 whitespace-pre-wrap rounded-lg bg-cold-900 p-4 text-sm text-text-secondary">{letter.content}</pre></details><div className="flex flex-wrap gap-2">{(letter.status === 'draft' || letter.status === 'rejected') && <Button size="sm" variant="outline" onClick={() => void submit(letter)}>Submit for review</Button>}{canApprove && letter.status === 'submitted' && <><Button size="sm" onClick={() => void decide(letter, 'approved')}>Approve</Button><Button size="sm" variant="outline" onClick={() => void decide(letter, 'rejected')}>Return with changes</Button></>}</div></div>)}</div>}</CardContent></Card>
    <Modal isOpen={eventOpen} onClose={() => setEventOpen(false)} title="Create a permission event" description="Use one event to generate letters for a selected roster." size="md"><form onSubmit={createEvent} className="space-y-4"><Input label="Event name" required value={eventForm.name} onChange={event => setEventForm({ ...eventForm, name: event.target.value })} /><div className="grid gap-4 sm:grid-cols-2"><Input label="Date" type="date" required value={eventForm.date} onChange={event => setEventForm({ ...eventForm, date: event.target.value })} /><Select label="Type" value={eventForm.type} onChange={event => setEventForm({ ...eventForm, type: event.target.value })} options={['competition', 'training_camp', 'travel', 'other'].map(value => ({ value, label: value.replace('_', ' ') }))} /></div><Input label="Venue" value={eventForm.venue} onChange={event => setEventForm({ ...eventForm, venue: event.target.value })} /><label className="block text-sm text-text-secondary">Purpose / details<textarea className="mt-1 min-h-16 w-full rounded-lg border border-border bg-cold-900 px-3 py-2 text-text-primary" value={eventForm.description} onChange={event => setEventForm({ ...eventForm, description: event.target.value })} /></label><div className="flex justify-end gap-2"><Button type="button" variant="ghost" onClick={() => setEventOpen(false)}>Cancel</Button><Button type="submit" loading={saving}>Create event</Button></div></form></Modal>
    <Modal isOpen={Boolean(generateFor)} onClose={() => setGenerateFor(null)} title={`Generate letters · ${generateFor?.name || ''}`} description="Choose participants and one or more letter types." size="lg"><div className="space-y-4"><div className="grid gap-2 sm:grid-cols-2">{athletes.map(athlete => <label key={athlete.id} className="flex items-center gap-2 rounded-lg border border-border p-3 text-sm text-text-primary"><input type="checkbox" checked={selectedAthletes.includes(athlete.id)} onChange={() => toggle(selectedAthletes, athlete.id, setSelectedAthletes)} />{athlete.firstName} {athlete.lastName}</label>)}</div><div><p className="mb-2 text-sm font-medium text-text-primary">Letter types</p><div className="grid gap-2 sm:grid-cols-2">{letterTypes.map(type => <label key={type.value} className="flex items-center gap-2 text-sm text-text-secondary"><input type="checkbox" checked={selectedTypes.includes(type.value)} onChange={() => toggle(selectedTypes, type.value, setSelectedTypes)} />{type.label}</label>)}</div></div><div className="flex justify-end gap-2"><Button variant="ghost" onClick={() => setGenerateFor(null)}>Cancel</Button><Button loading={saving} disabled={!selectedAthletes.length || !selectedTypes.length} onClick={() => void generateLetters()}>Generate {selectedAthletes.length * selectedTypes.length || ''} letters</Button></div></div></Modal>
    <Modal isOpen={createdOpen} onClose={() => setCreatedOpen(false)} title="Letters generated" description="Share or save verification links now. The raw verification token is only returned once." size="lg"><div className="max-h-[55vh] space-y-3 overflow-auto">{createdLinks.map(letter => <div key={letter.id} className="rounded-lg border border-border p-3"><div className="flex items-center justify-between gap-2"><p className="font-medium text-text-primary">{letter.athleteName} · {letter.templateId}</p><Button size="sm" variant="ghost" onClick={() => void copy(letter.verificationUrl)} leftIcon={<Clipboard className="h-4 w-4" />}>Copy verify link</Button></div><p className="mt-2 break-all text-xs text-text-muted">{letter.verificationUrl}</p></div>)}</div><div className="mt-4 flex justify-end"><Button onClick={() => { setCreatedOpen(false); setTab('letters'); }}>Done <Check className="ml-2 h-4 w-4" /></Button></div></Modal>
  </div>;
}
