import React, { FormEvent, useCallback, useEffect, useState } from 'react';
import { Bell, Megaphone, Pin, Plus } from 'lucide-react';
import { toast } from 'sonner';
import { Button, Card, CardContent, Modal } from '@/components/ui';
import { useAuth } from '@/context/AuthContext';
import { announcementApi } from '@/services/api';

export function Announcements() {
  const { hasPermission } = useAuth();
  const canPublish = hasPermission('announcement:write');
  const [items, setItems] = useState<any[]>([]); const [loading, setLoading] = useState(true); const [open, setOpen] = useState(false); const [saving, setSaving] = useState(false);
  const [title, setTitle] = useState(''); const [message, setMessage] = useState(''); const [audience, setAudience] = useState<string[]>(['athlete', 'coach']); const [pinned, setPinned] = useState(false);
  const load = useCallback(async () => { setLoading(true); try { setItems(await announcementApi.get()); } catch (error: any) { toast.error(error.message || 'Could not load updates'); } finally { setLoading(false); } }, []);
  useEffect(() => { void load(); }, [load]);
  const markRead = async (item: any) => { if (item.read) return; try { await announcementApi.markRead(item.id); setItems(previous => previous.map(row => row.id === item.id ? { ...row, read: true } : row)); } catch (error: any) { toast.error(error.message || 'Could not mark this update as read'); } };
  const submit = async (event: FormEvent) => { event.preventDefault(); setSaving(true); try { await announcementApi.create({ title, message, audience, pinned }); toast.success('Update published'); setOpen(false); setTitle(''); setMessage(''); await load(); } catch (error: any) { toast.error(error.message || 'Could not publish update'); } finally { setSaving(false); } };
  return <div className="mx-auto max-w-4xl space-y-6"><section className="surface-raised flex flex-col gap-4 p-6 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-sm font-semibold text-sky-400">CLUB UPDATES</p><h1 className="mt-2 text-3xl font-bold text-text-primary">Announcements</h1><p className="mt-2 text-text-secondary">Schedule changes and important messages shared with your club.</p></div>{canPublish && <Button onClick={() => setOpen(true)} leftIcon={<Plus className="h-4 w-4"/>}>Publish update</Button>}</section>
    {loading ? <div role="status" className="py-16 text-center text-text-secondary">Loading club updates…</div> : items.length ? <div className="space-y-3">{items.map(item => <Card key={item.id} className={!item.read ? 'border-sky-500/40' : ''}><CardContent className="p-5" onFocus={() => void markRead(item)} onMouseEnter={() => void markRead(item)}><div className="flex items-start gap-3"><div className="mt-1 rounded-lg bg-sky-500/10 p-2 text-sky-400"><Megaphone className="h-5 w-5"/></div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h2 className="font-semibold text-text-primary">{item.title}</h2>{item.pinned && <Pin className="h-4 w-4 text-amber-400"/>}{!item.read && <span className="rounded-full bg-sky-500 px-2 py-0.5 text-[10px] font-bold uppercase text-cold-950">New</span>}</div><p className="mt-2 whitespace-pre-wrap text-sm leading-6 text-text-secondary">{item.message}</p><p className="mt-3 text-xs text-text-muted">{item.publishedAt ? new Date(item.publishedAt).toLocaleString() : 'Recently'} · For {item.audience.join(', ').replaceAll('_', ' ')}</p></div></div></CardContent></Card>)}</div> : <Card><CardContent className="py-16 text-center"><Bell className="mx-auto h-10 w-10 text-text-muted"/><h2 className="mt-3 font-semibold text-text-primary">You’re all caught up</h2><p className="mt-1 text-sm text-text-secondary">New club messages will show up here.</p></CardContent></Card>}
    <Modal isOpen={open} onClose={() => setOpen(false)} title="Publish a club update" description="Choose the club roles that should see this message." size="md"><form className="space-y-4" onSubmit={submit}><label className="block text-sm text-text-secondary">Title<input required minLength={3} maxLength={160} className="mt-1 w-full rounded-lg border border-border bg-cold-900 px-3 py-2 text-text-primary" value={title} onChange={event => setTitle(event.target.value)}/></label><label className="block text-sm text-text-secondary">Message<textarea required minLength={3} maxLength={5000} rows={5} className="mt-1 w-full rounded-lg border border-border bg-cold-900 px-3 py-2 text-text-primary" value={message} onChange={event => setMessage(event.target.value)}/></label><fieldset><legend className="mb-2 text-sm text-text-secondary">Audience</legend><div className="flex flex-wrap gap-3">{['athlete','coach','club_admin'].map(role => <label key={role} className="flex items-center gap-2 text-sm capitalize text-text-primary"><input type="checkbox" checked={audience.includes(role)} onChange={event => setAudience(previous => event.target.checked ? [...previous, role] : previous.filter(value => value !== role))}/>{role.replace('_',' ')}</label>)}</div></fieldset><label className="flex items-center gap-2 text-sm text-text-primary"><input type="checkbox" checked={pinned} onChange={event => setPinned(event.target.checked)}/>Pin this update</label><div className="flex justify-end gap-2"><Button type="button" variant="ghost" onClick={() => setOpen(false)}>Cancel</Button><Button type="submit" loading={saving} disabled={!audience.length}>Publish</Button></div></form></Modal>
  </div>;
}
